### ISSUE TITLE
Gene program/marker expression score as metadata

### ISSUE THREAD

**Issue by bednarsky** [epigen/unsupervised_analysis#35]
What's the best way to directly visualize marker signature expression, e.g., to get a feeling for cell type assignment, in the unsupervised pipeline? My approach would have been to precalculate them and add them to the metadata. Is that sensible/intended?

**Comment by sreichl** [comment]
Yes, exactly. 

Context: the input (data & metadata) is intended to remain as little and general as possible, while still enabling most desired visualisations. Scores of any sort are "just" numeric metadata.

**Comment by sreichl** [comment]
PS: you can specify features of interest in the config (eg canonical markers) and they will be visualised like metadata one by one.
