### ISSUE TITLE
Segmentation fault bug with UMAP diagnostic step

### ISSUE THREAD

**Issue by JakeLehle** [epigen/unsupervised_analysis#53]
Hi Stephan

I really like the pipeline but I hit an error with the UMAP diagnostic step that I couldn't figure out when running the test data.
Here is the stderr.

I think the error is with the os.makedirs() on line 25 of the /workflow/scripts/plot_umap_diagnostics.py. 
I'm running this on a cluster so I figured it would be a group permission issue so I tried modifying the command to add in 

`
if not os.path.exists(result_dir):
    os.makedirs(result_dir, exist_ok=True, mode=0o775)
`
This didn't fix the error and still threw the segmentation fault.
I just can't see why there is a segmentation fault on the step of the pipeline. Maybe it's a C library install I'm not seeing which would make sense for it saying segmentation fault and not just "permission denied".

Any help would be great!

##############################################################################################

(snakemake_sc) -bash-4.2$ snakemake --use-conda --cores 2
Building DAG of jobs...
Your conda installation is not configured to use strict channel priorities. This is however crucial for having robust and correct environments (for details, see https://conda-forge.org/docs/user/tipsandtricks.html). Please consider to configure strict priorities by executing 'conda config --set channel_priority strict'.
Using shell: /usr/bin/bash
Provided cores: 2
Rules claiming more threads will be scaled down.
Job stats:

job                                 count
--------------------------------  -------
aggregate_all_clustering_results        1
aggregate_clustering_results            1
aggregate_rank_internal                 1
all                                     1
annot_export                            1
clustification                          1
clustree_analysis                       2
clustree_analysis_metadata              2
env_export                              1
plot_dimred_clustering                  3
plot_dimred_features                    3
plot_dimred_interactive                 6
plot_dimred_metadata                    3
plot_indices                            2
plot_pca_diagnostics                    1
plot_umap_connectivity                  2
plot_umap_diagnostics                   2
prep_feature_plot                       1
umap_embed                              1
validation_external                     1
validation_internal                     6
total                                  42

Select jobs to execute...

[Sat Jun 15 22:28:19 2024]
rule plot_umap_diagnostics:
    input: /master/jlehle/SC/mr.pareto/unsupervised_analysis/results/unsupervised_analysis/digits/densMAP/densMAP_euclidean_15_0.1_2_object.pickle
    output: /master/jlehle/SC/mr.pareto/unsupervised_analysis/results/unsupervised_analysis/digits/densMAP/plots/densMAP_euclidean_15_0.1_2_diagnostics.png
    log: logs/rules/plot_diagnostics_digits_densMAP_euclidean_15_0.1_2.log
    jobid: 30
    reason: Missing output files: /master/jlehle/SC/mr.pareto/unsupervised_analysis/results/unsupervised_analysis/digits/densMAP/plots/densMAP_euclidean_15_0.1_2_diagnostics.png
    wildcards: sample=digits, method=densMAP, parameters=euclidean_15_0.1_2
    threads: 2
    resources: tmpdir=/tmp, mem_mb=32000

Activating conda environment: ../../../anaconda3/bin/ca1be5fdd0af91990db4dd485b159f69_
Activating conda environment: ../../../anaconda3/bin/ca1be5fdd0af91990db4dd485b159f69_
/usr/bin/bash: line 1:   991 Segmentation fault      python /master/jlehle/SC/mr.pareto/unsupervised_analysis/.snakemake/scripts/tmps1pq2thb.plot_umap_diagnostics.py
[Sat Jun 15 22:28:39 2024]
Error in rule plot_umap_diagnostics:
    jobid: 30
    input: /master/jlehle/SC/mr.pareto/unsupervised_analysis/results/unsupervised_analysis/digits/densMAP/densMAP_euclidean_15_0.1_2_object.pickle
    output: /master/jlehle/SC/mr.pareto/unsupervised_analysis/results/unsupervised_analysis/digits/densMAP/plots/densMAP_euclidean_15_0.1_2_diagnostics.png
    log: logs/rules/plot_diagnostics_digits_densMAP_euclidean_15_0.1_2.log (check log file(s) for error details)
    conda-env: /master/jlehle/anaconda3/bin/ca1be5fdd0af91990db4dd485b159f69_

RuleException:
CalledProcessError in file /master/jlehle/SC/mr.pareto/unsupervised_analysis/workflow/rules/visualization.smk, line 122:
Command 'source /master/jlehle/anaconda3/envs/snakemake_sc/bin/activate '/master/jlehle/anaconda3/bin/ca1be5fdd0af91990db4dd485b159f69_'; set -euo pipefail;  python /master/jlehle/SC/mr.pareto/unsupervised_analysis/.snakemake/scripts/tmps1pq2thb.plot_umap_diagnostics.py' returned non-zero exit status 139.
  File "/master/jlehle/SC/mr.pareto/unsupervised_analysis/workflow/rules/visualization.smk", line 122, in __rule_plot_umap_diagnostics
  File "/master/jlehle/anaconda3/envs/snakemake_sc/lib/python3.10/concurrent/futures/thread.py", line 58, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-06-15T222813.460342.snakemake.log

**Comment by sreichl** [comment]
Hi Jake,
thanks for the kind words and for reporting the bug. If you like the workflow please consider starring and sharing, this helps others to find and benefit from the effort and me to prioritize my efforts!

Could you share the error log file of the failing job with me? Should/Could be here
- `logs/rules/plot_diagnostics_digits_densMAP_euclidean_15_0.1_2.log`
- `logs/rules/plot_diagnostics_digits_densMAP_euclidean_15_0.1_2.err`

Do you think it could be related to this reported bug #44 ?

Thanks & Cheers, Stephan

**Comment by JakeLehle** [comment]
Hello,

Yes I'm setting up the GitHub repo for a new lab I just joined and I working on incorporating the umbrella of MR.PARETO pipelines into it. After reading through the documentation, I think it's modularity is exactly what most labs are looking for as far as automating pipelines which will let biologists get back to doing the science an not worry so much about having to code a bunch of stuff. I'll definitely continue to try and contribute patches if I see any bugs or updates that can make this a more adopted platform.

SO back to the issue. 
I didn't get any .err files in the logs dir but I did get that
`logs/rules/plot_diagnostics_digits_densMAP_euclidean_15_0.1_2.log`
However, the file is empty when it is opened. So this again makes me think it's not a problem with the python script which should have output an err message into the log file but a C library problem which would make sense about the segmentation fault error being thrown right at the start of the rule. It likely needs an update to the env.yaml with the library I just have to track down which one.

I did see #44 before I made the issue and even tried changing the `diagnostic=0` to skip the step but it throws some additional subsequent errors like @bednarsky mentioned and I wanted to run the test data all the way through so I poke through all the outputs.

I'll spin up a test env soon and see if I can't manually troubleshoot the issue in more depth. I think when I start pulling in larger datasets I'll run into the #44 issue soon so it wouldn't hurt to be more familiar with the code in this step.

**Comment by sreichl** [comment]
Hi Jake,

- re MR.PARETO usage: great to hear the positive feedback. FYI: over the summer I will put up 1-2 more complementary MODULES and then start sharing RECIPES, which connect the MODULES in a meaningful way. Stay tuned. All feedback from early adopters is highly appreciated. Bug fixes etc. are of course amazing cherries on top.
- re empty log file: If you are using SLURM the .err file might be in a different folder than indicated by Snakemake (e.g., for me it's in `{repository}/logs/logs_slurm/`), depending on the cluster profile you are using.
- I expect to solve the issue this week and will push a fixed version tested on the example data.

Cheers, Stephan

**Comment by sreichl** [comment]
I hope I have solved this now by fixing package compatibilities/dependencies.

**Comment by JakeLehle** [comment]
Yes, this issue has now been fixed. Thank you so much!
