### ISSUE TITLE
Clustification slow since updating to snakemake 8 version of pipeline

### ISSUE THREAD

**Issue by bednarsky** [epigen/unsupervised_analysis#56]
Hi Stephan, 

- I have recently updated from older version of MrBiomics to the most recent version using snakemake v8.
- The clustification step for my a larger subset of my dataset used to take ~4 hours (for the largest subset of data)
- Now, for the largest subset, it doesn't finish within 12 hours
- It finished only for the smallest subset of my data (in 3 hours, used to take 15 min for this subset)
- I have changed nothing in the other other rules preceding this step

**Comment by sreichl** [comment]
Hm wouldn't know what one (Snakemake version) would have to do with the other (clustification). Did the specific job take longer or the overall process?

**Comment by bednarsky** [comment]
- This specific job, the rest finished as usual within reasonable times (so far)
- Also, according to the log file there is not a single iteration done (might also be that it just prints everything at the end of the process only?)

**Comment by sreichl** [comment]
@fwzhao literally just mentioned the same thing (something took far longer than before) just on ATAC-seq alignment so it might be a local cluster / hardware / SLURM issue?

**Comment by bednarsky** [comment]
In my case it seems to be because since smk8 the jobs that used multiple threads end up only using 1 core anymore - this is independed of whether I made a rule saying `threads: 8` or whether it's imported from MrBiomics (like for clustification here). Could this be due to `local-cores=1` in [cemm.slurm.sm/config.v8+.yaml](https://github.com/epigen/cemm.slurm.sm/blob/main/config.v8%2B.yaml)

**Comment by bednarsky** [comment]
Yes, seems to have been the issue. This works. 

```diff
  # Use spaces instead of tabs
  # sane defaults for CLI arguments
  executor: slurm
  jobs: 5000
+ cores: 100
  software-deployment-method: conda
  immediate-submit: false
  notemp: true
  restart-times: 0
  max-jobs-per-second: 10
  max-status-checks-per-second: 10
- local-cores: 1
  latency-wait: 120
  keep-going: true
  rerun-incomplete: true
  printshellcmds: true
  show-failed-logs: true
  
  
  # SLURM
  # Note that raw string arguments need double quotes (see slurm_extra)
  # Slurm parition and qos must match on the CeMM cluster.
  default-resources:
      # slurm_account, partition, and runtime are recommended.
      # match the CeMM intranet: https://cemmat.sharepoint.com/sites/IT-Resources/SitePages/Submitting-Slurm-Jobs.aspx
      slurm_account: lab_bock
      slurm_partition: tinyq
      slurm_extra: "'--qos=tinyq'" # Note the extra quoting!
      runtime: 120 # in minutes
  #     --kill-on-invalid-dep=yes # could be added to slurm_extra in case of immediate-submit: true
```

**Comment by sreichl** [comment]
https://github.com/epigen/cemm.slurm.sm/commit/64a2655ff31a31633079d0736e79ea6674302f6d

**Comment by sreichl** [comment]
thanks @bednarsky !
