### ISSUE TITLE
Error: No columns to parse from file Snakefile", line 25

### ISSUE THREAD

**Issue by bednarsky** [epigen/unsupervised_analysis#60]
- I get a really weird error in multiple jobs (different rules, not all jobs from a given rule, found no obvious patterns yet)
- Many jobs finish normally
- The whole logfile of a job with this error (not the conductor log!):
  > Injecting conda environment /path/to/other_repositories/MrBiomics/unsupervised_analysis/workflow/envs/global.yaml.
  > Injecting conda environment /path/to/other_repositories/MrBiomics/unsupervised_analysis/workflow/envs/global.yaml.
  > Injecting conda environment /path/to/other_repositories/MrBiomics/unsupervised_analysis/workflow/envs/global.yaml.
  > Injecting conda environment /path/to/other_repositories/MrBiomics/unsupervised_analysis/workflow/envs/global.yaml.
  > Injecting conda environment /path/to/other_repositories/MrBiomics/unsupervised_analysis/workflow/envs/global.yaml.
  > Injecting conda environment /path/to/other_repositories/MrBiomics/spilterlize_integrate/workflow/envs/global.yaml.
  > Injecting conda environment /path/to/other_repositories/MrBiomics/spilterlize_integrate/workflow/envs/global.yaml.
  > Injecting conda environment /path/to/other_repositories/MrBiomics/spilterlize_integrate/workflow/envs/global.yaml.
  > Injecting conda environment /path/to/other_repositories/MrBiomics/spilterlize_integrate/workflow/envs/global.yaml.
  > Injecting conda environment /path/to/other_repositories/MrBiomics/unsupervised_analysis/workflow/envs/global.yaml.
  > EmptyDataError in file /path/to/projects/proj_name/../../other_repositories/MrBiomics/unsupervised_analysis/workflow/Snakefile, line 25:
  > No columns to parse from file
  >   File "/path/to/projects/proj_name/../../other_repositories/MrBiomics/unsupervised_analysis/workflow/Snakefile", line 25, in <module>
  >   File "/path/to/miniconda3/envs/snakemake8_20_1/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
  >   File "/path/to/miniconda3/envs/snakemake8_20_1/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 620, in _read
  >   File "/path/to/miniconda3/envs/snakemake8_20_1/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
  >   File "/path/to/miniconda3/envs/snakemake8_20_1/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1898, in _make_engine
  >   File "/path/to/miniconda3/envs/snakemake8_20_1/lib/python3.12/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 93, in __init__
  >   File "parsers.pyx", line 581, in pandas._libs.parsers.TextReader.__cinit__

- it seems that this is about the line that loads the annot file, which is really weird, since this is already loaded when building the DAG in the conductor job, and that works fine. 
- Thus, the job never starts really
https://github.com/epigen/unsupervised_analysis/blob/f902effddc7b23e05e9093a4583833fa479a5763/workflow/Snakefile#L25
- similar issues, not the same: https://github.com/KarchinLab/2020plus/issues/7 &rarr; but our latency is already [quite high at 120](https://github.com/epigen/cemm.slurm.sm/blob/64a2655ff31a31633079d0736e79ea6674302f6d/config.v8%2B.yaml#L12) &rarr; anyways trying now to increase it to 1000 and running again

**Comment by sreichl** [comment]
is this maybe one of the annotation files you create during the whole workflow (which is not recommended)?

**Comment by bednarsky** [comment]
Different than expected, but yes, was the way I create the annotation files
More precisely, snakemake 8 (I believe this changed) seems to rerun all functions in the .smk files each time it starts a job - this lead to concurrency issues, when one job tried to overwrite the annot file (instead of, as I believed, running the function once in the beginning before building the DAG)
